### ISSUE TITLE
Dataset preparation

### ISSUE THREAD

**Issue by hadilou** [PatrickTUM/UnCRtainTS#1]
Hi,
Thanks for the nice work and accompanying article.  I got your code running with the _SEN12MS-CR-TS_ dataset but ideally I would like to run inference on my own dataset (let's say from a different region). Do you have a script to prepare the dataset for other locations?

**Comment by PatrickTUM** [comment]
Hi @hadilou,

great to see you interested in our work! If you'd like to apply our code on any other region of interest, you may try fetching your desired data via Google Earth Engine, or process any other data accordingly. We use [Sentinel-1](https://developers.google.com/earth-engine/guides/sentinel1) and [Sentinel-2 level 1-C](https://developers.google.com/earth-engine/datasets/catalog/COPERNICUS_S2) products, which are finally handled as specified in the [dataloader](https://github.com/PatrickTUM/UnCRtainTS/blob/main/data/dataLoader.py). Hoping this helps you! Cheers, Patrick

**Comment by GKG1312** [comment]
> Hi, Thanks for the nice work and accompanying article. I got your code running with the _SEN12MS-CR-TS_ dataset but ideally, I would like to run inference on my own dataset (let's say from a different region). Do you have a script to prepare the dataset for other locations?

Hi @hadilou ,
I am trying to run the method for the `SEN12MS-CR` dataset, but being new to this topic I am a little confused about how to arrange the data as per the test instruction. I want to use the following command line 
```
python test_reconstruct.py --experiment_name my_first_experiment -root1 path/to/SEN12MSCRtrain --root2 path/to/SEN12MSCRtest --root3 path/to/SEN12MSCR --input_t 3 --region all --export_every 1 --res_dir ./inference --weight_folder ./results
```
How do I separate data for `path/to/SEN12MSCRtrain`, `path/to/SEN12MSCRtest `, and `path/to/SEN12MSCR`? 
I have all the data as stored originally with folders and subfolders separating them based on season and sensors.

**Comment by PatrickTUM** [comment]
Hello @GKG1312

to use this command and the provided dataloader, the referenced data is expected to be in the structure as given by the [downloading script](https://github.com/PatrickTUM/UnCRtainTS/blob/main/util/dl_data.sh). If you wish to perform training or inference on the mono-temporal SEN12MS-CR dataset, then only the flag --root3 is relevant for you, set it to the directory containing your SEN12MS-CR dataset. You can find the meaning of flags briefly explained in the associated [parser script](https://github.com/PatrickTUM/UnCRtainTS/blob/main/model/parse_args.py). Hoping this helps!

Cheers,
Patrick

**Comment by GKG1312** [comment]
Thank you @PatrickTUM 
It was very helpful.

**Comment by starcksi** [comment]
Hi @hadilou and @GKG1312,

Did you find any way to run inference on new data?
