### ISSUE TITLE
How is the aleatoric uncertainty map calculated? 

### ISSUE THREAD

**Issue by try-agaaain** [PatrickTUM/UnCRtainTS#6]
Hello @PatrickTUM ,
Thank you for your great work!

In practical scenarios, how is the aleatoric uncertainty map calculated? According to the description in the paper, aleatoric uncertainty prediction comes from the diagonal covariance matrix. 
> ![image](https://github.com/PatrickTUM/UnCRtainTS/assets/52828870/ffd7da3b-3d37-4c6a-9c3f-3c820c4b5706)

So, is the Aleatoric uncertainty map calculated based on the network output results? Or if it is predicted by the network, how should the corresponding loss function be designed?

**Comment by PatrickTUM** [comment]
Hi @try-agaaain,

great seeing you interested in our work! The aleatoric uncertainty map is directly predicted by the network itself! The network's predictions at inference time, at each pixel (i,j) of the output map, are given by
- the 13 means (1 mean value for each band), which provide the reconstructed image and
- the 13 variances (1 variance value for each band), which provides a diagonal covariance matrix at each pixel

You can find the architecture's outputs defined [here](https://github.com/PatrickTUM/UnCRtainTS/blob/5e1f1b58e993645e765b64e10b6e9c7ff828b36f/model/src/backbones/uncrtaints.py#L438) and the NLL loss function is defined [here](https://github.com/PatrickTUM/UnCRtainTS/blob/5e1f1b58e993645e765b64e10b6e9c7ff828b36f/model/src/losses.py#L149) (but also see the other lines of code in said file).

Hoping this helps!
Patrick
